# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
generic-service:
  replicaCount: 2

  ingress:
    host: digital-preprod.prison.service.justice.gov.uk

  env:
    PRISON_STAFF_HUB_UI_URL: https://digital-preprod.prison.service.justice.gov.uk/
    HMPPS_COOKIE_DOMAIN: digital-preprod.prison.service.justice.gov.uk
    API_ENDPOINT_URL: https://prison-api-preprod.prison.service.justice.gov.uk/
    OAUTH_ENDPOINT_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth/
    HMPPS_MANAGE_USERS_API_URL: https://manage-users-api-preprod.hmpps.service.justice.gov.uk
    API_WHEREABOUTS_ENDPOINT_URL: https://whereabouts-api-preprod.service.justice.gov.uk/
    API_LOCATIONS_INSIDE_PRISON_ENDPOINT_URL: https://locations-inside-prison-api-preprod.hmpps.service.justice.gov.uk
    API_NOMIS_MAPPING_ENDPOINT_URL: https://nomis-sync-prisoner-mapping-preprod.hmpps.service.justice.gov.uk
    LICENCES_URL: https://licences-preprod.prison.service.justice.gov.uk/
    HMPPS_COOKIE_NAME: hmpps-session-preprod
    API_DELIUS_ENDPOINT_URL: https://dps-and-delius-preprod.hmpps.service.justice.gov.uk
    API_DATA_COMPLIANCE_ENDPOINT_URL: https://prison-data-compliance-preprod.prison.service.justice.gov.uk
    CATEGORISATION_UI_URL: https://preprod.offender-categorisation.service.justice.gov.uk/
    USE_OF_FORCE_URL: https://preprod.use-of-force.service.justice.gov.uk
    USE_OF_FORCE_PRISONS: "ACI,AGI,ASI,AYI,BAI,BCI,BFI,BHI,BLI,BMI,BNI,BRI,BSI,BWI,BXI,BZI,CDI,CFI,CLI,CWI,DAI,DGI,DHI,DMI,DNI,DTI,DWI,EEI,EHI,ESI,EWI,EXI,EYI,FBI,FDI,FEI,FHI,FKI,FMI,FNI,FSI,FWI,GHI,GMI,GNI,GTI,HBI,HCI,HDI,HEI,HHI,HII,HLI,HMI,HOI,HPI,HVI,ISI,IWI,KMI,KVI,LCI,LEI,LFI,LGI,LHI,LII,LLI,LNI,LPI,LTI,LWI,LYI,MDI,MHI,MRI,MSI,MTI,NHI,NLI,NMI,NSI,NWI,ONI,OWI,PBI,PDI,PFI,PNI,PRI,PVI,RCI,RHI,RNI,RSI,SDI,SFI,SHI,SKI,SLI,SNI,SPI,STI,SUI,SWI,TCI,TSI,UKI,UPI,VEI,WCI,WDI,WEI,WHI,WII,WLI,WMI,WRI,WSI,WTI,WWI,MKI"
    CHECK_MY_DIARY_URL: https://check-my-diary-preprod.prison.service.justice.gov.uk?fromDPS=true
    INCENTIVES_URL: https://incentives-ui-preprod.hmpps.service.justice.gov.uk
    TOKENVERIFICATION_API_URL: https://token-verification-api-preprod.prison.service.justice.gov.uk
    CASENOTES_API_URL: https://preprod.offender-case-notes.service.justice.gov.uk/
    PIN_PHONES_URL: https://pcms-qa.prison.service.justice.gov.uk/
    OFFENDER_SEARCH_API_URL: https://prisoner-search-preprod.prison.service.justice.gov.uk
    SUPPORT_URL: https://support-preprod.hmpps.service.justice.gov.uk/
    SYSTEM_PHASE: PRE-PRODUCTION
    BVL_URL: https://book-a-video-link-preprod.prison.service.justice.gov.uk
    BOOK_A_VIDEO_LINK_API_URL: https://book-a-video-link-api-preprod.prison.service.justice.gov.uk
    MOIC_URL: https://preprod.moic.service.justice.gov.uk
    OMIC_URL: https://preprod.manage-key-workers.service.justice.gov.uk
    MANAGE_AUTH_ACCOUNTS_URL: https://manage-users-preprod.hmpps.service.justice.gov.uk
    PECS_URL: http://hmpps-book-secure-move-frontend-preprod.apps.cloud-platform.service.justice.gov.uk
    MANAGE_ADJUDICATIONS_URL: https://manage-adjudications-preprod.hmpps.service.justice.gov.uk/
    MANAGE_RESTRICTED_PATIENTS_URL: https://manage-restricted-patients-preprod.hmpps.service.justice.gov.uk/
    ESWE_ENABLED: true
    NEURODIVERSITY_ENABLED_USERNAMES: 'NCLAMP_GEN,CN004364,DBULL_GEN'
    NEURODIVERSITY_ENABLED_PRISONS: "BLI,NHI,LII,SLI"
    CURIOUS_URL: https://preprodservices.sequation.net/sequation-virtual-campus2-api/
    DISABLE_REQUEST_LIMITER: true
    MANAGE_PRISON_VISITS_URL: https://manage-prison-visits-preprod.prison.service.justice.gov.uk/
    LEGACY_PRISON_VISITS_URL: https://prison-visits-booking-staff-staging.apps.live.cloud-platform.service.justice.gov.uk/
    CALCULATE_RELEASE_DATES_URL: https://calculate-release-dates-preprod.hmpps.service.justice.gov.uk
    SEND_LEGAL_MAIL_URL: https://check-rule39-mail-preprod.prison.service.justice.gov.uk
    WELCOME_PEOPLE_INTO_PRISON_URL: https://welcome-preprod.prison.service.justice.gov.uk/
    MERCURY_SUBMIT_URL: https://submit-a-mercury-report-preprod.hmpps.service.justice.gov.uk/
    MERCURY_SUBMIT_PRIVATE_BETA_ENABLED_DATE: 2023-06-01T02:00:00
    MERCURY_SUBMIT_PRIVATE_BETA_ENABLED_PRISONS: "LNI,FHI,BZI,SDI,GTI,BAI,MRI,NMI,RNI,SUI,SKI"
    MERCURY_SUBMIT_LIVE_ENABLED_DATE: ""
    CREATE_AND_VARY_A_LICENCE_URL: https://create-and-vary-a-licence-preprod.hmpps.service.justice.gov.uk/
    CREATE_AND_VARY_A_LICENCE_ENABLED_PRISONS: "ACI,AGI,ASI,AYI,BAI,BCI,BFI,BLI,BMI,BNI,BRI,BSI,BWI,BXI,BZI,CDI,CFI,CKI,CLI,CWI,DAI,DGI,DHI,DMI,DNI,DTI,DWI,EEI,EHI,ESI,EWI,EXI,EYI,FBI,FDI,FEI,FHI,FKI,FMI,FNI,FSI,FWI,GHI,GMI,GNI,HBI,HCI,HDI,HEI,HHI,HII,HLI,HMI,HOI,HPI,HVI,ISI,IWI,KMI,KVI,LCI,LEI,LFI,LGI,LHI,LII,LLI,LNI,LPI,LTI,LWI,LYI,MDI,MHI,MRI,MSI,MTI,NHI,NLI,NMI,NSI,NWI,ONI,OWI,PBI,PDI,PFI,PNI,PRI,PVI,RCI,RHI,RNI,RSI,SDI,SFI,SHI,SKI,SLI,SNI,SPI,STI,SUI,SWI,TCI,TSI,UKI,UPI,VEI,WCI,WDI,WEI,WHI,WII,WLI,WMI,WRI,WSI,WTI,WWI"
    ACTIVITIES_URL: https://activities-preprod.prison.service.justice.gov.uk/activities
    ACTIVITIES_ENABLED_PRISONS: "RSI,WDI,LPI,FMI,IWI,WMI,GTI,FKI,LTI,BCI,FNI,MTI,LEI,FSI,DMI,HII,WII,RCI,RNI,MDI,LFI,LHI,EYI,PDI,SLI,SNI,BXI,NMI,PVI,WEI,WSI,VEI,BLI,HOI,PNI,CFI,DWI,LCI,ISI,HEI,MHI,AYI,BRI,BSI,BAI,BNI,WLI,WHI,WTI,CLI,MRI,ONI,LII,GHI,SFI,SKI,SHI,WCI,EXI,HCI,EEI,MSI,HLI,BFI,EWI,LLI,HMI,GMI,HBI,DTI,WWI,HHI,LWI,CWI,SDI,BWI,NWI,FHI,WRI,DHI,NHI,STI,CKI,CDI,BMI,HPI"
    APPOINTMENTS_URL: https://activities-preprod.prison.service.justice.gov.uk/appointments
    APPOINTMENTS_ENABLED_PRISONS: "RSI,WDI,LPI,FMI,IWI,WMI,GTI,FKI,LTI,BCI,FNI,MTI,LEI,FSI,DMI,HII,WII,RCI,RNI,MDI,LFI,LHI,EYI,PDI,SLI,SNI,BXI,NMI,PVI,WEI,WSI,VEI,BLI,HOI,PNI,CFI,DWI,LCI,ISI,HEI,MHI,AYI,BRI,BSI,BAI,BNI,WLI,WHI,WTI,CLI,MRI,ONI,LII,GHI,SFI,SKI,SHI,WCI,EXI,HCI,EEI,MSI,HLI,BFI,EWI,LLI,HMI,GMI,HBI,DTI,WWI,HHI,LWI,CWI,SDI,BWI,NWI,FHI,WRI,DHI,NHI,STI,CKI,CDI,BMI,HPI"
    RESTRICTED_PATIENT_API_URL: https://restricted-patients-api-preprod.hmpps.service.justice.gov.uk/
    HISTORICAL_PRISONER_APPLICATION_URL: https://historical-prisoner-preprod.prison.service.justice.gov.uk
    WHEREABOUTS_MAINTENANCE_MODE: false
    COVID_UNITS_ENABLED: false
    GET_SOMEONE_READY_FOR_WORK_URL: https://get-ready-for-work-preprod.hmpps.service.justice.gov.uk
    LEARNING_AND_WORK_PROGRESS_URL: https://ciag-induction-preprod.hmpps.service.justice.gov.uk
    PRISONER_PROFILE_REDIRECT_URL: https://prisoner-preprod.digital.prison.service.justice.gov.uk
    HOMEPAGE_REDIRECT_URL: http://dps-preprod.prison.service.justice.gov.uk
    HOMEPAGE_REDIRECT_ENABLED_DATE: ""
    HOMEPAGE_REDIRECT_ENABLED_PRISONS: "ACI,AGI,ASI,AYI,BAI,BCI,BFI,BLI,BMI,BNI,BRI,BSI,BWI,BXI,BZI,CDI,CFI,CKI,CLI,CWI,DAI,DGI,DHI,DMI,DNI,DTI,DWI,EEI,EHI,ESI,EWI,EXI,EYI,FBI,FDI,FEI,FHI,FKI,FMI,FNI,FSI,FWI,FYI,GHI,GMI,GNI,GTI,HBI,HCI,HDI,HEI,HHI,HII,HLI,HMI,HOI,HPI,HVI,ISI,IWI,KMI,KTI,KVI,LCI,LEI,LFI,LGI,LHI,LII,LLI,LNI,LPI,LTI,LWI,LYI,MDI,MHI,MRI,MSI,MTI,MWI,NHI,NLI,NMI,NSI,NWI,ONI,OWI,PBI,PDI,PFI,PNI,PRI,PVI,PYI,RCI,RHI,RNI,RSI,SDI,SFI,SHI,SKI,SLI,SNI,SPI,STI,SUI,SWI,TCI,TSI,UKI,UPI,VEI,WCI,WDI,WEI,WHI,WII,WLI,WMI,WNI,WRI,WSI,WTI,WWI,WYI"
    HOMEPAGE_SCHEDULE_REDIRECT_FOR_PRISONS: ""
    MANAGE_OFFENCES_URL: https://manage-offences-preprod.hmpps.service.justice.gov.uk
    MANAGE_ADJUDICATIONS_API_URL: https://manage-adjudications-api-preprod.hmpps.service.justice.gov.uk
    COMPONENT_API_URL: https://frontend-components-preprod.hmpps.service.justice.gov.uk
    COMPONENT_API_LATEST: false
    PREPARE_SOMEONE_FOR_RELEASE_URL: https://resettlement-passport-ui-preprod.hmpps.service.justice.gov.uk
    HOMEPAGE_REDIRECT_EXEMPTIONS: ""
    VIDEO_CONFERENCE_SCHEDULE_URL: https://video-conference-schedule-preprod.prison.service.justice.gov.uk
    CHANGE_SOMEONES_CELL_URL: https://change-someones-cell-preprod.prison.service.justice.gov.uk
    SUNSET_BANNER_ENABLED: true
    ALERTS_API_URL: "https://alerts-api-preprod.hmpps.service.justice.gov.uk"

  allowlist:
    palo-alto-prisma-corporate: 128.77.75.64/26
    groups:
      - internal
      - prisons
      - private_prisons

generic-prometheus-alerts:
  alertSeverity: hmpps-activities-management-preprod
