# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  repository: quay.io/hmpps/prisonstaffhub
  tag: latest
  pullPolicy: IfNotPresent
  port: 3000

ingress:
  enabled: true
  enable_allowlist: true
  host: digital-preprod.prison.service.justice.gov.uk
  cert_secret: notm-cert
  path: /
  host2: whereabouts-preprod.prison.service.justice.gov.uk
  cert_secret2: prison-staff-hub-cert
  redirect_host2: https://digital-preprod.prison.service.justice.gov.uk

env:
  API_ENDPOINT_URL: https://api-preprod.prison.service.justice.gov.uk/
  OAUTH_ENDPOINT_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth/
  API_WHEREABOUTS_ENDPOINT_URL: https://whereabouts-api-preprod.service.justice.gov.uk/
  LICENCES_URL: https://licences-preprod.prison.service.justice.gov.uk/
  HMPPS_COOKIE_NAME: hmpps-session-preprod
  REMOTE_AUTH_STRATEGY: "true"
  WEB_SESSION_TIMEOUT_IN_MINUTES: "60"
  API_COMMUNITY_ENDPOINT_URL: https://community-api-secure.pre-prod.delius.probation.hmpps.dsd.io
  API_COMMUNITY_API_PREFIX: "/secure"
  API_DATA_COMPLIANCE_ENDPOINT_URL: https://prison-data-compliance-preprod.prison.service.justice.gov.uk
  KEYWORKER_API_URL: https://keyworker-api-preprod.prison.service.justice.gov.uk/
  CATEGORISATION_UI_URL: https://preprod.offender-categorisation.service.justice.gov.uk/
  USE_OF_FORCE_URL: https://preprod.use-of-force.service.justice.gov.uk
  USE_OF_FORCE_PRISONS: "ACI,AGI,ASI,AYI,BAI,BCI,BFI,BHI,BLI,BMI,BNI,BRI,BSI,BWI,BXI,BZI,CDI,CFI,CLI,CWI,DAI,DGI,DHI,DMI,DNI,DTI,DWI,EEI,EHI,ESI,EWI,EXI,EYI,FBI,FDI,FHI,FKI,FMI,FNI,FSI,GHI,GMI,GNI,GTI,HBI,HCI,HDI,HEI,HHI,HII,HLI,HMI,HOI,HPI,HVI,ISI,IWI,KMI,KVI,LCI,LEI,LFI,LGI,LHI,LII,LLI,LNI,LPI,LTI,LWI,LYI,MDI,MHI,MRI,MSI,MTI,NHI,NLI,NMI,NSI,NWI,ONI,OWI,PBI,PDI,PFI,PNI,PRI,PVI,RCI,RHI,RNI,RSI,SDI,SFI,SHI,SKI,SLI,SNI,SPI,STI,SUI,SWI,TCI,TSI,UKI,UPI,VEI,WCI,WDI,WEI,WHI,WII,WLI,WMI,WRI,WSI,WTI,WWI"
  TOKENVERIFICATION_API_URL: https://token-verification-api-preprod.prison.service.justice.gov.uk
  TOKENVERIFICATION_API_ENABLED: true
  CASENOTES_API_URL: https://preprod.offender-case-notes.service.justice.gov.uk/
  ALLOCATION_MANAGER_ENDPOINT_URL: https://allocation-manager-preprod.apps.live-1.cloud-platform.service.justice.gov.uk/
  PATHFINDER_UI_URL: https://preprod.pathfinder.service.justice.gov.uk/
  PATHFINDER_ENDPOINT_API_URL: https://preprod-api.pathfinder.service.justice.gov.uk/
  PIN_PHONES_URL: https://pin-phone-monitor-qa.prison.service.justice.gov.uk/
  REDIS_ENABLED: true
  SOC_UI_URL: https://manage-soc-cases-preprod.hmpps.service.justice.gov.uk/
  SOC_API_URL: https://manage-soc-cases-api-preprod.hmpps.service.justice.gov.uk/
  SOC_API_ENABLED: true
  OFFENDER_SEARCH_API_URL: https://prisoner-offender-search-preprod.prison.service.justice.gov.uk
  SUPPORT_URL: https://support-preprod.hmpps.service.justice.gov.uk/
  SYSTEM_PHASE: PRE-PRODUCTION
  BVL_URL: https://book-video-link-preprod.prison.service.justice.gov.uk
  MOIC_URL: https://allocation-manager-preprod.apps.live-1.cloud-platform.service.justice.gov.uk
  OMIC_URL: https://preprod.manage-key-workers.service.justice.gov.uk
  MANAGE_AUTH_ACCOUNTS_URL: https://manage-hmpps-auth-accounts-preprod.prison.service.justice.gov.uk
  PECS_URL: http://hmpps-book-secure-move-frontend-preprod.apps.live-1.cloud-platform.service.justice.gov.uk
  COMPLEXITY_OF_NEED_URI: https://complexity-of-need-preprod.hmpps.service.justice.gov.uk
  PRISONS_WITH_OFFENDERS_THAT_HAVE_COMPLEX_NEEDS: "AGI,BZI,DHI,DWI,ESI,EWI,FHI,LNI,NHI,PFI,SDI,STI"
  ESWE_ENABLED: false
  CURIOUS_URL: https://testservices.sequation.net/sequation-virtual-campus2-api/

allowlist:
  office: "217.33.148.210/32"
  quantum: "62.25.109.197/32"
  quantum_alt: "212.137.36.230/32"
  health-kick: "35.177.252.195/32"
  digitalprisons1: "52.56.112.98/32"
  digitalprisons2: "52.56.118.154/32"
  mojvpn: "81.134.202.29/32"
  j5-phones-1: "35.177.125.252/32"
  j5-phones-2: "35.177.137.160/32"
  sodexo-northumberland: "88.98.48.10/32"
  sodexo-northumberland2: "51.148.47.137/32"
  sodoxeo-forest-bank: "51.155.85.249/32"
  sodexo-peterborough: "51.155.55.241/32"
  serco: "217.22.14.0/24"
  ark-nps-hmcts-ttp1: "195.59.75.0/24"
  ark-nps-hmcts-ttp2: "194.33.192.0/25"
  ark-nps-hmcts-ttp3: "194.33.193.0/25"
  ark-nps-hmcts-ttp4: "194.33.196.0/25"
  ark-nps-hmcts-ttp5: "194.33.197.0/25"
  oakwood-1: "217.161.76.187/32"
  oakwood-2: "217.161.76.195/32"
  oakwood-3: "217.161.76.186/32"
  oakwood-4: "217.161.76.194/32"
  durham-tees-valley: "51.179.197.1/32"
  interservfls: "51.179.196.131/32"
  sodexo1: "80.86.46.16/32"
  sodexo2: "80.86.46.17/32"
  sodexo3: "80.86.46.18/32"
  cloudplatform-live1-1: "35.178.209.113/32"
  cloudplatform-live1-2: "3.8.51.207/32"
  cloudplatform-live1-3: "35.177.252.54/32"
  dxc_webproxy1: "195.92.38.20/32"
  dxc_webproxy2: "195.92.38.21/32"
  dxc_webproxy3: "195.92.38.22/32"
  dxc_webproxy4: "195.92.38.23/32"
  moj-official-tgw-prod: "51.149.250.0/24"
  moj-official-tgw-preprod: "51.149.251.0/24"
  crc-rrp: "62.253.83.37/32"
  crc-pp-wwm: "5.153.255.210/32"
