# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: quay.io/hmpps/prisonstaffhub
  tag: latest
  pullPolicy: IfNotPresent
  port: 3000

ingress:
  enabled: true
  enable_whitelist: false
  host: digital-dev.prison.service.justice.gov.uk
  cert_secret: notm-cert
  path: /
  host2: whereabouts-dev.prison.service.justice.gov.uk
  cert_secret2: prison-staff-hub-cert
  redirect_host2: https://digital-dev.prison.service.justice.gov.uk

env:
  API_ENDPOINT_URL: https://api-dev.prison.service.justice.gov.uk/
  OAUTH_ENDPOINT_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth/
  API_WHEREABOUTS_ENDPOINT_URL: https://whereabouts-api-dev.service.justice.gov.uk/
  LICENCES_URL: https://licences-dev.prison.service.justice.gov.uk/
  HMPPS_COOKIE_NAME: hmpps-session-dev
  REMOTE_AUTH_STRATEGY: "true"
  WEB_SESSION_TIMEOUT_IN_MINUTES: "60"
  API_COMMUNITY_ENDPOINT_URL: https://community-api-secure.test.delius.probation.hmpps.dsd.io
  API_COMMUNITY_API_PREFIX: "/secure"
  API_DATA_COMPLIANCE_ENDPOINT_URL: https://prison-data-compliance-dev.prison.service.justice.gov.uk/
  DISPLAY_RETENTION_LINK: "true"
  KEYWORKER_API_URL: https://keyworker-api-dev.prison.service.justice.gov.uk/
  CATEGORISATION_UI_URL: https://dev.offender-categorisation.service.justice.gov.uk/
  USE_OF_FORCE_URL: https://dev.use-of-force.service.justice.gov.uk
  USE_OF_FORCE_PRISONS: "WRI,MDI"
  TOKENVERIFICATION_API_URL: https://token-verification-api-dev.prison.service.justice.gov.uk
  TOKENVERIFICATION_API_ENABLED: true
  CASENOTES_API_URL: https://dev.offender-case-notes.service.justice.gov.uk/
  ALLOCATION_MANAGER_ENDPOINT_URL: https://allocation-manager-staging.apps.live-1.cloud-platform.service.justice.gov.uk/
  PATHFINDER_UI_URL: https://dev.pathfinder.service.justice.gov.uk/
  PATHFINDER_ENDPOINT_API_URL: https://dev-api.pathfinder.service.justice.gov.uk/
  PIN_PHONES_URL: https://pin-phone-monitor-dev.prison.service.justice.gov.uk/
  REDIS_ENABLED: true
  SOC_UI_URL: https://manage-soc-cases-dev.hmpps.service.justice.gov.uk/
  SOC_API_URL: https://manage-soc-cases-api-dev.hmpps.service.justice.gov.uk/
  SOC_API_ENABLED: true
  OFFENDER_SEARCH_API_URL: https://prisoner-offender-search-dev.prison.service.justice.gov.uk
  SUPPORT_URL: https://support-dev.hmpps.service.justice.gov.uk/
  ESWE_ENABLED: true
  CURIOUS_URL: https://testservices.sequation.net/sequation-virtual-campus2-api/

  SYSTEM_PHASE: DEV
  BVL_URL: https://book-video-link-dev.prison.service.justice.gov.uk
  MOIC_URL: https://allocation-manager-staging.apps.live-1.cloud-platform.service.justice.gov.uk
  OMIC_URL: https://dev.manage-key-workers.service.justice.gov.uk
  MANAGE_AUTH_ACCOUNTS_URL: https://manage-hmpps-auth-accounts-dev.prison.service.justice.gov.uk
  PECS_URL: https://hmpps-book-secure-move-frontend-staging.apps.live-1.cloud-platform.service.justice.gov.uk
  COMPLEXITY_OF_NEED_URI: https://complexity-of-need-staging.hmpps.service.justice.gov.uk
  PRISONS_WITH_OFFENDERS_THAT_HAVE_COMPLEX_NEEDS: "MDI,LEI"
