# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
generic-service:
  replicaCount: 2

  ingress:
   host: digital-dev.prison.service.justice.gov.uk 

  allowlist: false 

  env:
   PRISON_STAFF_HUB_UI_URL: https://digital-dev.prison.service.justice.gov.uk/
   HMPPS_COOKIE_DOMAIN: digital-dev.prison.service.justice.gov.uk
   API_ENDPOINT_URL: https://api-dev.prison.service.justice.gov.uk/
   OAUTH_ENDPOINT_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth/
   API_WHEREABOUTS_ENDPOINT_URL: https://whereabouts-api-dev.service.justice.gov.uk/
   LICENCES_URL: https://licences-dev.prison.service.justice.gov.uk/
   HMPPS_COOKIE_NAME: hmpps-session-dev
   API_COMMUNITY_ENDPOINT_URL: https://community-api-secure.test.delius.probation.hmpps.dsd.io
   API_DATA_COMPLIANCE_ENDPOINT_URL: https://prison-data-compliance-dev.prison.service.justice.gov.uk/
   DISPLAY_RETENTION_LINK: "true"
   KEYWORKER_API_URL: https://keyworker-api-dev.prison.service.justice.gov.uk/
   CATEGORISATION_UI_URL: https://dev.offender-categorisation.service.justice.gov.uk/
   USE_OF_FORCE_URL: https://dev.use-of-force.service.justice.gov.uk
   USE_OF_FORCE_PRISONS: "FWI,MDI,WRI"
   CHECK_MY_DIARY_URL: https://check-my-diary-dev.prison.service.justice.gov.uk?fromDPS=true
   INCENTIVES_URL: https://incentives-ui-dev.hmpps.service.justice.gov.uk
   INCENTIVES_API_ENDPOINT_URL: https://incentives-api-dev.hmpps.service.justice.gov.uk
   INCENTIVES_EXCLUDED_CASELOADS: "CADM_I"
   INCENTIVES_DATA_IS_MASTER: true
   TOKENVERIFICATION_API_URL: https://token-verification-api-dev.prison.service.justice.gov.uk
   CASENOTES_API_URL: https://dev.offender-case-notes.service.justice.gov.uk/
   ALLOCATION_MANAGER_ENDPOINT_URL: https://dev.moic.service.justice.gov.uk/
   PATHFINDER_UI_URL: https://dev.pathfinder.service.justice.gov.uk/
   PATHFINDER_ENDPOINT_API_URL: https://dev-api.pathfinder.service.justice.gov.uk/
   PIN_PHONES_URL: https://pcms-dev.prison.service.justice.gov.uk/
   SOC_UI_URL: https://manage-soc-cases-dev.hmpps.service.justice.gov.uk/
   SOC_API_URL: https://manage-soc-cases-api-dev.hmpps.service.justice.gov.uk/
   OFFENDER_SEARCH_API_URL: https://prisoner-offender-search-dev.prison.service.justice.gov.uk
   SUPPORT_URL: https://support-dev.hmpps.service.justice.gov.uk/
   ESWE_ENABLED: false
   NEURODIVERSITY_ENABLED_USERNAMES: ""
   NEURODIVERSITY_ENABLED_PRISONS: "BLI,NHI,LII,SLI"
   CURIOUS_URL: https://testservices.sequation.net/sequation-virtual-campus2-api/
   SYSTEM_PHASE: DEV
   BVL_URL: https://book-video-link-dev.prison.service.justice.gov.uk
   MOIC_URL: https://dev.moic.service.justice.gov.uk
   OMIC_URL: https://dev.manage-key-workers.service.justice.gov.uk
   MANAGE_AUTH_ACCOUNTS_URL: https://manage-users-dev.hmpps.service.justice.gov.uk
   PECS_URL: https://hmpps-book-secure-move-frontend-staging.apps.live-1.cloud-platform.service.justice.gov.uk
   COMPLEXITY_OF_NEED_URI: https://complexity-of-need-staging.hmpps.service.justice.gov.uk
   PRISONS_WITH_OFFENDERS_THAT_HAVE_COMPLEX_NEEDS: "MDI,LEI"
   PRISONS_WITH_MANAGE_ADJUDICATIONS_ENABLED: "MDI"
   PRISONS_FOR_MANAGE_PRISON_BOOKINGS: "HEI"
   MANAGE_ADJUDICATIONS_URL: https://manage-adjudications-dev.hmpps.service.justice.gov.uk/
   MANAGE_RESTRICTED_PATIENTS_URL: https://manage-restricted-patients-dev.hmpps.service.justice.gov.uk/
   MANAGE_PRISON_VISITS_URL: https://manage-prison-visits-dev.prison.service.justice.gov.uk/
   LEGACY_PRISON_VISITS_URL: https://prison-visits-booking-staff-dev.apps.live.cloud-platform.service.justice.gov.uk/
   CALCULATE_RELEASE_DATES_URL: https://calculate-release-dates-dev.hmpps.service.justice.gov.uk
   SEND_LEGAL_MAIL_URL: https://check-rule39-mail-dev.prison.service.justice.gov.uk
   WELCOME_PEOPLE_INTO_PRISON_URL: https://welcome-dev.prison.service.justice.gov.uk/
   CREATE_AND_VARY_A_LICENCE_URL: https://create-and-vary-a-licence-dev.hmpps.service.justice.gov.uk/
   CREATE_AND_VARY_A_LICENCE_ENABLED_PRISONS: "MDI,LEI,LPI,BMI,PVI,BXI,WAI"
   RESTRICTED_PATIENT_API_URL: https://restricted-patients-api-dev.hmpps.service.justice.gov.uk/
   HISTORICAL_PRISONER_APPLICATION_URL: 	https://hpa-stage.hmpps.dsd.io
