# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
generic-service:
  replicaCount: 4

  ingress:
    host: digital.prison.service.justice.gov.uk

  env:
   PRISON_STAFF_HUB_UI_URL: https://digital.prison.service.justice.gov.uk/
   HMPPS_COOKIE_DOMAIN: digital.prison.service.justice.gov.uk
   API_ENDPOINT_URL: https://api.prison.service.justice.gov.uk/
   OAUTH_ENDPOINT_URL: https://sign-in.hmpps.service.justice.gov.uk/auth/
   HMPPS_MANAGE_USERS_API_URL: https://manage-users-api.hmpps.service.justice.gov.uk
   API_WHEREABOUTS_ENDPOINT_URL: https://whereabouts-api.service.justice.gov.uk/
   LICENCES_URL: https://licences.prison.service.justice.gov.uk/
   HMPPS_COOKIE_NAME: hmpps-session-preprod
   API_COMMUNITY_ENDPOINT_URL: https://community-api-secure.probation.service.justice.gov.uk
   KEYWORKER_API_URL: https://keyworker-api.prison.service.justice.gov.uk/
   CATEGORISATION_UI_URL: https://offender-categorisation.service.justice.gov.uk/
   USE_OF_FORCE_URL: https://use-of-force.service.justice.gov.uk
   USE_OF_FORCE_PRISONS: "ACI,AGI,ASI,AYI,BAI,BCI,BFI,BHI,BLI,BMI,BNI,BRI,BSI,BWI,BXI,BZI,CDI,CFI,CLI,CWI,DAI,DGI,DHI,DMI,DNI,DTI,DWI,EEI,EHI,ESI,EWI,EXI,EYI,FBI,FDI,FEI,FHI,FKI,FMI,FNI,FSI,FWI,GHI,GMI,GNI,GTI,HBI,HCI,HDI,HEI,HHI,HII,HLI,HMI,HOI,HPI,HVI,ISI,IWI,KMI,KVI,LCI,LEI,LFI,LGI,LHI,LII,LLI,LNI,LPI,LTI,LWI,LYI,MDI,MHI,MRI,MSI,MTI,NHI,NLI,NMI,NSI,NWI,ONI,OWI,PBI,PDI,PFI,PNI,PRI,PVI,RCI,RHI,RNI,RSI,SDI,SFI,SHI,SKI,SLI,SNI,SPI,STI,SUI,SWI,TCI,TSI,UKI,UPI,VEI,WCI,WDI,WEI,WHI,WII,WLI,WMI,WRI,WSI,WTI,WWI"
   CHECK_MY_DIARY_URL: https://checkmydiary.service.justice.gov.uk?fromDPS=true
   INCENTIVES_URL: https://incentives-ui.hmpps.service.justice.gov.uk
   INCENTIVES_API_ENDPOINT_URL: https://incentives-api.hmpps.service.justice.gov.uk
   NON_ASSOCIATIONS_PRISONS: "FNI,ISI,LGI,RSI"
   NON_ASSOCIATIONS_API_ENDPOINT_URL: https://non-associations-api.hmpps.service.justice.gov.uk
   NON_ASSOCIATIONS_UI_URL: https://non-associations.hmpps.service.justice.gov.uk
   TOKENVERIFICATION_API_URL: https://token-verification-api.prison.service.justice.gov.uk
   CASENOTES_API_URL: https://offender-case-notes.service.justice.gov.uk/
   ALLOCATION_MANAGER_ENDPOINT_URL: https://moic.service.justice.gov.uk/
   PATHFINDER_UI_URL: https://pathfinder.service.justice.gov.uk/
   PATHFINDER_ENDPOINT_API_URL: https://api.pathfinder.service.justice.gov.uk/
   PIN_PHONES_URL: https://pcms.prison.service.justice.gov.uk/
   SOC_UI_URL: https://manage-soc-cases.hmpps.service.justice.gov.uk/
   SOC_API_URL: https://manage-soc-cases-api.hmpps.service.justice.gov.uk/
   OFFENDER_SEARCH_API_URL: https://prisoner-offender-search.prison.service.justice.gov.uk
   SUPPORT_URL: https://support.hmpps.service.justice.gov.uk/
   BVL_URL: https://book-video-link.prison.service.justice.gov.uk
   MOIC_URL: https://moic.service.justice.gov.uk
   OMIC_URL: https://manage-key-workers.service.justice.gov.uk
   MANAGE_AUTH_ACCOUNTS_URL: https://manage-users.hmpps.service.justice.gov.uk
   PECS_URL: https://bookasecuremove.service.justice.gov.uk
   COMPLEXITY_OF_NEED_URI: https://complexity-of-need.hmpps.service.justice.gov.uk
   PRISONS_WITH_OFFENDERS_THAT_HAVE_COMPLEX_NEEDS: "AGI,BZI,DHI,DWI,ESI,EWI,FHI,LNI,NHI,PFI,SDI,STI"
   PRISONS_WITH_MANAGE_ADJUDICATIONS_ENABLED: "RNI,WLI,MDI,EXI,BXI,PVI,NHI,DMI,BLI,LFI,NSI,SWI,BNI,STI,SPI,SUI,BSI,LWI"
   MANAGE_ADJUDICATIONS_URL: https://manage-adjudications.hmpps.service.justice.gov.uk/
   MANAGE_RESTRICTED_PATIENTS_URL: https://manage-restricted-patients.hmpps.service.justice.gov.uk/
   ESWE_ENABLED: true
   NEURODIVERSITY_ENABLED_USERNAMES: "CN004364,DBULL_GEN,J_DRAPER"
   NEURODIVERSITY_ENABLED_PRISONS: "BLI,NHI,LII,SLI"
   CURIOUS_URL: https://liveservices.sequation.com/sequation-virtual-campus2-api/
   DISABLE_REQUEST_LIMITER: true
   MANAGE_PRISON_VISITS_URL: https://manage-prison-visits.prison.service.justice.gov.uk/
   LEGACY_PRISON_VISITS_URL: https://staff.prisonvisits.service.justice.gov.uk/
   SECURE_SOCIAL_VIDEO_CALLS_URL: https://auth.phonehub.io/accounts/login/oauth/redirect/
   CALCULATE_RELEASE_DATES_URL: https://calculate-release-dates.hmpps.service.justice.gov.uk
   SEND_LEGAL_MAIL_URL: https://check-rule39-mail.prison.service.justice.gov.uk
   WELCOME_PEOPLE_INTO_PRISON_URL: https://welcome.prison.service.justice.gov.uk/
   MERCURY_SUBMIT_URL: https://submit-a-mercury-report.hmpps.service.justice.gov.uk/
   MERCURY_SUBMIT_PRIVATE_BETA_URL: https://submit-a-mercury-report.hmpps.service.justice.gov.uk/
   MERCURY_SUBMIT_PRIVATE_BETA_ENABLED_DATE: 2023-07-04T02:00:00
   MERCURY_SUBMIT_PRIVATE_BETA_ENABLED_PRISONS: "LNI,FHI,BZI,SDI,GTI,BAI,MRI,NMI,RNI,SUI,SKI"
   MERCURY_SUBMIT_LIVE_ENABLED_DATE: 2023-07-26T02:00:00
   CREATE_AND_VARY_A_LICENCE_URL: https://create-and-vary-a-licence.hmpps.service.justice.gov.uk/
   CREATE_AND_VARY_A_LICENCE_ENABLED_PRISONS: "ACI,AGI,ASI,AYI,BAI,BCI,BFI,BLI,BMI,BNI,BRI,BSI,BWI,BXI,BZI,CDI,CFI,CKI,CLI,CWI,DAI,DGI,DHI,DMI,DNI,DTI,DWI,EEI,EHI,ESI,EWI,EXI,EYI,FBI,FDI,FEI,FHI,FKI,FMI,FNI,FSI,FWI,GHI,GMI,GNI,HBI,HCI,HDI,HEI,HHI,HII,HLI,HMI,HOI,HPI,HVI,ISI,IWI,KMI,KVI,LCI,LEI,LFI,LGI,LHI,LII,LLI,LNI,LPI,LTI,LWI,LYI,MDI,MHI,MRI,MSI,MTI,NHI,NLI,NMI,NSI,NWI,ONI,OWI,PBI,PDI,PFI,PNI,PRI,PVI,RCI,RHI,RNI,RSI,SDI,SFI,SHI,SKI,SLI,SNI,SPI,STI,SUI,SWI,TCI,TSI,UKI,UPI,VEI,WCI,WDI,WEI,WHI,WII,WLI,WMI,WRI,WSI,WTI,WWI"
   ACTIVITIES_URL: https://activities.prison.service.justice.gov.uk/activities
   ACTIVITIES_ENABLED_PRISONS: "RSI"
   APPOINTMENTS_URL: https://activities.prison.service.justice.gov.uk/appointments
   APPOINTMENTS_ENABLED_PRISONS: "RSI"
   RESTRICTED_PATIENT_API_URL: https://restricted-patients-api.hmpps.service.justice.gov.uk/
   HISTORICAL_PRISONER_APPLICATION_URL: https://hpa.service.hmpps.dsd.io
   WHEREABOUTS_MAINTENANCE_MODE: false
   KEYWORKER_MAINTENANCE_MODE: false
   GET_SOMEONE_READY_FOR_WORK_URL: https://get-ready-for-work.hmpps.service.justice.gov.uk
   LEARNING_AND_WORK_PROGRESS_URL: https://ciag-induction.hmpps.service.justice.gov.uk
   WARRANT_FOLDER_URL: https://manage-a-warrant-folder.hmpps.service.justice.gov.uk/
   PRISONER_PROFILE_REDIRECT_URL: https://prisoner.digital.prison.service.justice.gov.uk
   PRISONER_PROFILE_REDIRECT_ENABLED_DATE: 2023-09-29T18:00:00
   PRISONER_PROFILE_REDIRECT_ENABLED_PRISONS: "LEI,FNI,HMI,NHI,WDI,WEI,HLI,MDI,LHI,HDI,WYI,AGI,DNI,RSI"
   PRISONER_PROFILE_SCHEDULE_REDIRECT_FOR_PRISONS: "RSI"
   HOMEPAGE_REDIRECT_URL: http://dps.prison.service.justice.gov.uk
   HOMEPAGE_REDIRECT_ENABLED_DATE: 2023-10-16T02:00:00
   HOMEPAGE_REDIRECT_ENABLED_PRISONS: "FNI"
   HOMEPAGE_SCHEDULE_REDIRECT_FOR_PRISONS: "FNI"
   MANAGE_OFFENCES_URL: https://manage-offences.hmpps.service.justice.gov.uk
   MANAGE_ADJUDICATIONS_API_URL: https://manage-adjudications-api.hmpps.service.justice.gov.uk
   COMPONENT_API_URL: https://frontend-components.hmpps.service.justice.gov.uk
   COMPONENT_API_LATEST: false
   PREPARE_SOMEONE_FOR_RELEASE_URL: https://resettlement-passport-ui.hmpps.service.justice.gov.uk

  allowlist:
   office: "217.33.148.210/32"
   quantum: "62.25.109.197/32"
   petty-france-wifi: "213.121.161.112/28"
   global-protect: "35.176.93.186/32"
   quantum_alt: "212.137.36.230/32"
   health-kick: "35.177.252.195/32"
   digitalprisons1: "52.56.112.98/32"
   digitalprisons2: "52.56.118.154/32"
   mojvpn: "81.134.202.29/32"
   j5-phones-1: "35.177.125.252/32"
   j5-phones-2: "35.177.137.160/32"
   sodexo-northumberland: "88.98.48.10/32"
   sodexo-northumberland2: "51.148.47.137/32"
   sodoxeo-forest-bank: "51.155.85.249/32"
   sodexo-peterborough: "51.155.55.241/32"
   serco: "217.22.14.0/24"
   ark-nps-hmcts-ttp1: "195.59.75.0/24"
   ark-nps-hmcts-ttp2: "194.33.192.0/25"
   ark-nps-hmcts-ttp3: "194.33.193.0/25"
   ark-nps-hmcts-ttp4: "194.33.196.0/25"
   ark-nps-hmcts-ttp5: "194.33.197.0/25"
   oakwood-01: "217.161.76.184/29"
   oakwood-02: "217.161.76.192/29"
   oakwood-1: "217.161.76.187/32"
   oakwood-2: "217.161.76.195/32"
   oakwood-3: "217.161.76.186/32"
   oakwood-4: "217.161.76.194/32"
   durham-tees-valley: "51.179.197.1/32"
   interservfls: "51.179.196.131/32"
   sodexo1: "80.86.46.16/32"
   sodexo2: "80.86.46.17/32"
   sodexo3: "80.86.46.18/32"
   sodexo4: "51.148.9.201"
   cloudplatform-live1-1: "35.178.209.113/32"
   cloudplatform-live1-2: "3.8.51.207/32"
   cloudplatform-live1-3: "35.177.252.54/32"
   dxc_webproxy1: "195.92.38.20/32"
   dxc_webproxy2: "195.92.38.21/32"
   dxc_webproxy3: "195.92.38.22/32"
   dxc_webprox23: "195.92.38.23/32"
   moj-official-tgw-prod: "51.149.250.0/24"
   moj-official-tgw-preprod: "51.149.251.0/24"
   crc-rrp: "62.253.83.37/32"
   crc-pp-wwm: "5.153.255.210/32"
   moj-official-ark-c-expo-e: "51.149.249.0/29"
   moj-official-ark-c-vodafone: "194.33.248.0/29"
   moj-official-ark-f-vodafone: "194.33.249.0/29"
   moj-official-ark-f-expo-e: "51.149.249.32/29"
   met-police-talktalk-vpn-1: "212.139.143.66/32"
   met-police-talktalk-vpn-2: "212.74.97.221/32"
   met-police-vodafone-1: "195.27.18.79/32"
   met-police-vodafone-2: "195.27.18.110/32"
   met-police-vodafone-3: "195.80.67.207/32"
   police-1: "81.144.174.115/32"
   police-2: "81.144.241.238/32"
   police-3: "62.252.202.50/32"
   police-4-1: "80.194.71.100/32"
   police-4-2: "82.33.248.165/32"
   police-5: "52.56.62.0/24"
   police-6: "80.193.134.32/32"
   police-7: "195.92.38.21/32"
   police-8: "80.193.128.200/32"
   police-9: "194.73.161.50/32"
   police-10: "165.225.81.49/32"
   police-11: "195.89.175.213/32"
   police-12: "195.89.175.229/32"
   police-northants-1: "212.250.136.96/27"
   police-northants-2: "213.106.80.32/27"
   police-west-york-1: "195.188.22.0/27"
   police-west-york-2: "195.188.22.128/27"
   police-west-york-3: "195.89.14.37"
   police-west-york-4: "195.27.188.37"
   police-south-york-public: "80.193.114.10"
   police-south-york-mossway: "51.231.157.126"
   police-south-york-atlas: "51.231.157.222"
   police-humberside-public: "80.100.176.162"
   police-humberside-priory: "51.231.157.226"
   sscl-blackpool: "31.121.5.27"
   sscl-azure: "51.142.106.199"
   sscl-york: "62.6.61.29"
   sscl-newcastle: "62.172.79.105"
   sscl-newport: "217.38.237.212"
   fivewells-1: "195.89.157.56/29"
   fivewells-2: "195.59.215.184/29"
   fivewells-3: "51.149.250.0/24"
   fivewells-4: "51.149.249.0/29"
   fivewells-5: "194.33.249.0/29"
   fivewells-6: "51.149.249.32/29"
   fivewells-7: "194.33.248.0/29"
   mojo-azure-landing-zone-public-egress-1: "20.49.214.199/32"
   mojo-azure-landing-zone-public-egress-2: "20.49.214.228/32"
   mojo-azure-landing-zone-public-egress-3: "20.26.11.71/32"
   mojo-azure-landing-zone-public-egress-4: "20.26.11.108/32"

# determine which slack channel alerts are sent to, via the correct Alert Manager receiver
generic-prometheus-alerts:
  alertSeverity: digital-prison-service
